import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import useTranslation from "next-translate/useTranslation";
import Layout from "../components/Layout";

export default function Home() {
  const { t } = useTranslation();

  let router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Internationalization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>{t("common:greeting")}</h1>
      </Layout>
    </div>
  );
}
